/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.validation;

import com.chor4integration.textdsl.validation.AbstractChor4IntTxtDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslValidator extends AbstractChor4IntTxtDslValidator {
}
