/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ui.tests;

import com.chor4integration.textdsl.ui.internal.TextdslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Chor4IntTxtDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextdslActivator.getInstance().getInjector("com.chor4integration.textdsl.Chor4IntTxtDsl");
	}

}
