/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ui;

import com.chor4integration.textdsl.ui.AbstractChor4IntTxtDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Chor4IntTxtDslUiModule extends AbstractChor4IntTxtDslUiModule {
  public Chor4IntTxtDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
