/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl;

import com.chor4integration.textdsl.AbstractChor4IntTxtDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslRuntimeModule extends AbstractChor4IntTxtDslRuntimeModule {
}
