/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl;

import com.chor4integration.textdsl.Chor4IntTxtDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslStandaloneSetup extends Chor4IntTxtDslStandaloneSetupGenerated {
  public static void doSetup() {
    new Chor4IntTxtDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
