/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.tests

import com.chor4integration.chor4int.Choreography
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(Chor4IntTxtDslInjectorProvider)
class Chor4IntTxtDslParsingTest {
	@Inject
	ParseHelper<Choreography> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
