/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.scoping;

import com.chor4integration.textdsl.scoping.AbstractChor4IntTxtDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslScopeProvider extends AbstractChor4IntTxtDslScopeProvider {
}
