/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Chor4IntTxtDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/chor4integration/textdsl/parser/antlr/internal/InternalChor4IntTxtDsl.tokens");
	}
}
