/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.parser.antlr;

import com.chor4integration.textdsl.parser.antlr.internal.InternalChor4IntTxtDslParser;
import com.chor4integration.textdsl.services.Chor4IntTxtDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Chor4IntTxtDslParser extends AbstractAntlrParser {

	@Inject
	private Chor4IntTxtDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalChor4IntTxtDslParser createParser(XtextTokenStream stream) {
		return new InternalChor4IntTxtDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Choreography";
	}

	public Chor4IntTxtDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Chor4IntTxtDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
