/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Chor4IntTxtDslStandaloneSetup extends Chor4IntTxtDslStandaloneSetupGenerated {

	def static void doSetup() {
		new Chor4IntTxtDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
