/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Chor4IntTxtDslRuntimeModule extends AbstractChor4IntTxtDslRuntimeModule {
}
