/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractChor4IntTxtDslScopeProvider extends DelegatingScopeProvider {
}
