/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ide;

import com.chor4integration.textdsl.Chor4IntTxtDslRuntimeModule;
import com.chor4integration.textdsl.Chor4IntTxtDslStandaloneSetup;
import com.chor4integration.textdsl.ide.Chor4IntTxtDslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslIdeSetup extends Chor4IntTxtDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    Chor4IntTxtDslRuntimeModule _chor4IntTxtDslRuntimeModule = new Chor4IntTxtDslRuntimeModule();
    Chor4IntTxtDslIdeModule _chor4IntTxtDslIdeModule = new Chor4IntTxtDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_chor4IntTxtDslRuntimeModule, _chor4IntTxtDslIdeModule));
  }
}
