/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ide;

import com.chor4integration.textdsl.ide.AbstractChor4IntTxtDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslIdeModule extends AbstractChor4IntTxtDslIdeModule {
}
