/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ide


/**
 * Use this class to register ide components.
 */
class Chor4IntTxtDslIdeModule extends AbstractChor4IntTxtDslIdeModule {
}
