/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class Chor4IntTxtDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ChoreographyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Choreography");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cChoreographyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cChoreographyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFlowElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cFlowElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cFlowElementsFlowElementParserRuleCall_3_2_0 = (RuleCall)cFlowElementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cFlowElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cFlowElementsFlowElementParserRuleCall_3_3_1_0 = (RuleCall)cFlowElementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Choreography:
		//	{Choreography}
		//	'Choreography'
		//	'{' ('flowElements' '{' flowElements+=FlowElement ("," flowElements+=FlowElement)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Choreography} 'Choreography' '{' ('flowElements' '{' flowElements+=FlowElement ("," flowElements+=FlowElement)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Choreography}
		public Action getChoreographyAction_0() { return cChoreographyAction_0; }
		
		//'Choreography'
		public Keyword getChoreographyKeyword_1() { return cChoreographyKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('flowElements' '{' flowElements+=FlowElement ("," flowElements+=FlowElement)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'flowElements'
		public Keyword getFlowElementsKeyword_3_0() { return cFlowElementsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//flowElements+=FlowElement
		public Assignment getFlowElementsAssignment_3_2() { return cFlowElementsAssignment_3_2; }
		
		//FlowElement
		public RuleCall getFlowElementsFlowElementParserRuleCall_3_2_0() { return cFlowElementsFlowElementParserRuleCall_3_2_0; }
		
		//("," flowElements+=FlowElement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//flowElements+=FlowElement
		public Assignment getFlowElementsAssignment_3_3_1() { return cFlowElementsAssignment_3_3_1; }
		
		//FlowElement
		public RuleCall getFlowElementsFlowElementParserRuleCall_3_3_1_0() { return cFlowElementsFlowElementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FlowElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.FlowElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSequenceFlowParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExclusiveGatewayParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cParallelGatewayParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cStartEventParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEndEventParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cAtomicInteractionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//FlowElement:
		//	SequenceFlow | ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction;
		@Override public ParserRule getRule() { return rule; }
		
		//SequenceFlow | ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SequenceFlow
		public RuleCall getSequenceFlowParserRuleCall_0() { return cSequenceFlowParserRuleCall_0; }
		
		//ExclusiveGateway
		public RuleCall getExclusiveGatewayParserRuleCall_1() { return cExclusiveGatewayParserRuleCall_1; }
		
		//ParallelGateway
		public RuleCall getParallelGatewayParserRuleCall_2() { return cParallelGatewayParserRuleCall_2; }
		
		//StartEvent
		public RuleCall getStartEventParserRuleCall_3() { return cStartEventParserRuleCall_3; }
		
		//EndEvent
		public RuleCall getEndEventParserRuleCall_4() { return cEndEventParserRuleCall_4; }
		
		//AtomicInteraction
		public RuleCall getAtomicInteractionParserRuleCall_5() { return cAtomicInteractionParserRuleCall_5; }
	}
	public class FlowNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.FlowNode");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExclusiveGatewayParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParallelGatewayParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStartEventParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEndEventParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cAtomicInteractionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//FlowNode:
		//	ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction;
		@Override public ParserRule getRule() { return rule; }
		
		//ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExclusiveGateway
		public RuleCall getExclusiveGatewayParserRuleCall_0() { return cExclusiveGatewayParserRuleCall_0; }
		
		//ParallelGateway
		public RuleCall getParallelGatewayParserRuleCall_1() { return cParallelGatewayParserRuleCall_1; }
		
		//StartEvent
		public RuleCall getStartEventParserRuleCall_2() { return cStartEventParserRuleCall_2; }
		
		//EndEvent
		public RuleCall getEndEventParserRuleCall_3() { return cEndEventParserRuleCall_3; }
		
		//AtomicInteraction
		public RuleCall getAtomicInteractionParserRuleCall_4() { return cAtomicInteractionParserRuleCall_4; }
	}
	public class ActorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Actor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cServiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUserParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Actor servicesmetamodel::Actor:
		//	Service | User;
		@Override public ParserRule getRule() { return rule; }
		
		//Service | User
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Service
		public RuleCall getServiceParserRuleCall_0() { return cServiceParserRuleCall_0; }
		
		//User
		public RuleCall getUserParserRuleCall_1() { return cUserParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SequenceFlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.SequenceFlow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSequenceFlowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTargetKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTargetFlowNodeCrossReference_4_0 = (CrossReference)cTargetAssignment_4.eContents().get(0);
		private final RuleCall cTargetFlowNodeEStringParserRuleCall_4_0_1 = (RuleCall)cTargetFlowNodeCrossReference_4_0.eContents().get(1);
		private final Keyword cSourceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSourceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSourceFlowNodeCrossReference_6_0 = (CrossReference)cSourceAssignment_6.eContents().get(0);
		private final RuleCall cSourceFlowNodeEStringParserRuleCall_6_0_1 = (RuleCall)cSourceFlowNodeCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//SequenceFlow:
		//	'SequenceFlow'
		//	name=EString
		//	'{'
		//	'target' target=[FlowNode|EString]
		//	'source' source=[FlowNode|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SequenceFlow' name=EString '{' 'target' target=[FlowNode|EString] 'source' source=[FlowNode|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'SequenceFlow'
		public Keyword getSequenceFlowKeyword_0() { return cSequenceFlowKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'target'
		public Keyword getTargetKeyword_3() { return cTargetKeyword_3; }
		
		//target=[FlowNode|EString]
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }
		
		//[FlowNode|EString]
		public CrossReference getTargetFlowNodeCrossReference_4_0() { return cTargetFlowNodeCrossReference_4_0; }
		
		//EString
		public RuleCall getTargetFlowNodeEStringParserRuleCall_4_0_1() { return cTargetFlowNodeEStringParserRuleCall_4_0_1; }
		
		//'source'
		public Keyword getSourceKeyword_5() { return cSourceKeyword_5; }
		
		//source=[FlowNode|EString]
		public Assignment getSourceAssignment_6() { return cSourceAssignment_6; }
		
		//[FlowNode|EString]
		public CrossReference getSourceFlowNodeCrossReference_6_0() { return cSourceFlowNodeCrossReference_6_0; }
		
		//EString
		public RuleCall getSourceFlowNodeEStringParserRuleCall_6_0_1() { return cSourceFlowNodeEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ExclusiveGatewayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.ExclusiveGateway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExclusiveGatewayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExclusiveGatewayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_2_0 = (CrossReference)cIncomingsAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_3_1_0 = (CrossReference)cIncomingsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_2_0 = (CrossReference)cOutgoingsAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_3_1_0 = (CrossReference)cOutgoingsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ExclusiveGateway:
		//	{ExclusiveGateway}
		//	'ExclusiveGateway'
		//	name=EString
		//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
		//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExclusiveGateway} 'ExclusiveGateway' name=EString '{' ('incomings' '(' incomings+=[SequenceFlow|EString] (","
		//incomings+=[SequenceFlow|EString])* ')')? ('outgoings' '(' outgoings+=[SequenceFlow|EString] (","
		//outgoings+=[SequenceFlow|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ExclusiveGateway}
		public Action getExclusiveGatewayAction_0() { return cExclusiveGatewayAction_0; }
		
		//'ExclusiveGateway'
		public Keyword getExclusiveGatewayKeyword_1() { return cExclusiveGatewayKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incomings'
		public Keyword getIncomingsKeyword_4_0() { return cIncomingsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_2() { return cIncomingsAssignment_4_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_2_0() { return cIncomingsSequenceFlowCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1; }
		
		//("," incomings+=[SequenceFlow|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_3_1() { return cIncomingsAssignment_4_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_3_1_0() { return cIncomingsSequenceFlowCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoings' '(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoings'
		public Keyword getOutgoingsKeyword_5_0() { return cOutgoingsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_2() { return cOutgoingsAssignment_5_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_2_0() { return cOutgoingsSequenceFlowCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoings+=[SequenceFlow|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_3_1() { return cOutgoingsAssignment_5_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_3_1_0() { return cOutgoingsSequenceFlowCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ParallelGatewayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.ParallelGateway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParallelGatewayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParallelGatewayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_2_0 = (CrossReference)cIncomingsAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_3_1_0 = (CrossReference)cIncomingsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_2_0 = (CrossReference)cOutgoingsAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_3_1_0 = (CrossReference)cOutgoingsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ParallelGateway:
		//	{ParallelGateway}
		//	'ParallelGateway'
		//	name=EString
		//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
		//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ParallelGateway} 'ParallelGateway' name=EString '{' ('incomings' '(' incomings+=[SequenceFlow|EString] (","
		//incomings+=[SequenceFlow|EString])* ')')? ('outgoings' '(' outgoings+=[SequenceFlow|EString] (","
		//outgoings+=[SequenceFlow|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ParallelGateway}
		public Action getParallelGatewayAction_0() { return cParallelGatewayAction_0; }
		
		//'ParallelGateway'
		public Keyword getParallelGatewayKeyword_1() { return cParallelGatewayKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incomings'
		public Keyword getIncomingsKeyword_4_0() { return cIncomingsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_2() { return cIncomingsAssignment_4_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_2_0() { return cIncomingsSequenceFlowCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1; }
		
		//("," incomings+=[SequenceFlow|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_3_1() { return cIncomingsAssignment_4_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_3_1_0() { return cIncomingsSequenceFlowCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoings' '(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoings'
		public Keyword getOutgoingsKeyword_5_0() { return cOutgoingsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_2() { return cOutgoingsAssignment_5_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_2_0() { return cOutgoingsSequenceFlowCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoings+=[SequenceFlow|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_3_1() { return cOutgoingsAssignment_5_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_3_1_0() { return cOutgoingsSequenceFlowCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class StartEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.StartEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStartEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStartEventKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_2_0 = (CrossReference)cIncomingsAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_3_1_0 = (CrossReference)cIncomingsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_2_0 = (CrossReference)cOutgoingsAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_3_1_0 = (CrossReference)cOutgoingsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StartEvent:
		//	{StartEvent}
		//	'StartEvent'
		//	name=EString
		//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
		//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{StartEvent} 'StartEvent' name=EString '{' ('incomings' '(' incomings+=[SequenceFlow|EString] (","
		//incomings+=[SequenceFlow|EString])* ')')? ('outgoings' '(' outgoings+=[SequenceFlow|EString] (","
		//outgoings+=[SequenceFlow|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{StartEvent}
		public Action getStartEventAction_0() { return cStartEventAction_0; }
		
		//'StartEvent'
		public Keyword getStartEventKeyword_1() { return cStartEventKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incomings'
		public Keyword getIncomingsKeyword_4_0() { return cIncomingsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_2() { return cIncomingsAssignment_4_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_2_0() { return cIncomingsSequenceFlowCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1; }
		
		//("," incomings+=[SequenceFlow|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_3_1() { return cIncomingsAssignment_4_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_3_1_0() { return cIncomingsSequenceFlowCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoings' '(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoings'
		public Keyword getOutgoingsKeyword_5_0() { return cOutgoingsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_2() { return cOutgoingsAssignment_5_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_2_0() { return cOutgoingsSequenceFlowCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoings+=[SequenceFlow|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_3_1() { return cOutgoingsAssignment_5_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_3_1_0() { return cOutgoingsSequenceFlowCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EndEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.EndEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEndEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEndEventKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_2_0 = (CrossReference)cIncomingsAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingsSequenceFlowCrossReference_4_3_1_0 = (CrossReference)cIncomingsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_2_0 = (CrossReference)cOutgoingsAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_5_3_1_0 = (CrossReference)cOutgoingsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EndEvent:
		//	{EndEvent}
		//	'EndEvent'
		//	name=EString
		//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
		//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{EndEvent} 'EndEvent' name=EString '{' ('incomings' '(' incomings+=[SequenceFlow|EString] (","
		//incomings+=[SequenceFlow|EString])* ')')? ('outgoings' '(' outgoings+=[SequenceFlow|EString] (","
		//outgoings+=[SequenceFlow|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{EndEvent}
		public Action getEndEventAction_0() { return cEndEventAction_0; }
		
		//'EndEvent'
		public Keyword getEndEventKeyword_1() { return cEndEventKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incomings'
		public Keyword getIncomingsKeyword_4_0() { return cIncomingsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_2() { return cIncomingsAssignment_4_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_2_0() { return cIncomingsSequenceFlowCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_2_0_1; }
		
		//("," incomings+=[SequenceFlow|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_4_3_1() { return cIncomingsAssignment_4_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_4_3_1_0() { return cIncomingsSequenceFlowCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoings' '(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoings'
		public Keyword getOutgoingsKeyword_5_0() { return cOutgoingsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_2() { return cOutgoingsAssignment_5_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_2_0() { return cOutgoingsSequenceFlowCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoings+=[SequenceFlow|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_5_3_1() { return cOutgoingsAssignment_5_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_5_3_1_0() { return cOutgoingsSequenceFlowCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AtomicInteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.AtomicInteraction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAtomicInteractionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIncomingsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cIncomingsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cIncomingsSequenceFlowCrossReference_3_2_0 = (CrossReference)cIncomingsAssignment_3_2.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_3_2_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cIncomingsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cIncomingsSequenceFlowCrossReference_3_3_1_0 = (CrossReference)cIncomingsAssignment_3_3_1.eContents().get(0);
		private final RuleCall cIncomingsSequenceFlowEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cIncomingsSequenceFlowCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOutgoingsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOutgoingsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_4_2_0 = (CrossReference)cOutgoingsAssignment_4_2.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_4_2_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOutgoingsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cOutgoingsSequenceFlowCrossReference_4_3_1_0 = (CrossReference)cOutgoingsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cOutgoingsSequenceFlowEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cOutgoingsSequenceFlowCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cSenderKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSenderAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSenderRoleCrossReference_6_0 = (CrossReference)cSenderAssignment_6.eContents().get(0);
		private final RuleCall cSenderRoleEStringParserRuleCall_6_0_1 = (RuleCall)cSenderRoleCrossReference_6_0.eContents().get(1);
		private final Keyword cReceiverKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReceiverAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cReceiverRoleCrossReference_8_0 = (CrossReference)cReceiverAssignment_8.eContents().get(0);
		private final RuleCall cReceiverRoleEStringParserRuleCall_8_0_1 = (RuleCall)cReceiverRoleCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTargetOperationKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTargetOperationAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cTargetOperationOperationCrossReference_9_1_0 = (CrossReference)cTargetOperationAssignment_9_1.eContents().get(0);
		private final RuleCall cTargetOperationOperationEStringParserRuleCall_9_1_0_1 = (RuleCall)cTargetOperationOperationCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//AtomicInteraction:
		//	'AtomicInteraction'
		//	name=EString
		//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
		//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		//	'sender' sender=[servicesmetamodel::Role|EString]
		//	'receiver' receiver=[servicesmetamodel::Role|EString] ('targetOperation'
		//	targetOperation=[servicesmetamodel::Operation|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'AtomicInteraction' name=EString '{' ('incomings' '(' incomings+=[SequenceFlow|EString] (","
		//incomings+=[SequenceFlow|EString])* ')')? ('outgoings' '(' outgoings+=[SequenceFlow|EString] (","
		//outgoings+=[SequenceFlow|EString])* ')')? 'sender' sender=[servicesmetamodel::Role|EString] 'receiver'
		//receiver=[servicesmetamodel::Role|EString] ('targetOperation' targetOperation=[servicesmetamodel::Operation|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'AtomicInteraction'
		public Keyword getAtomicInteractionKeyword_0() { return cAtomicInteractionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'incomings'
		public Keyword getIncomingsKeyword_3_0() { return cIncomingsKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_3_2() { return cIncomingsAssignment_3_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_3_2_0() { return cIncomingsSequenceFlowCrossReference_3_2_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_3_2_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_3_2_0_1; }
		
		//("," incomings+=[SequenceFlow|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//incomings+=[SequenceFlow|EString]
		public Assignment getIncomingsAssignment_3_3_1() { return cIncomingsAssignment_3_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getIncomingsSequenceFlowCrossReference_3_3_1_0() { return cIncomingsSequenceFlowCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getIncomingsSequenceFlowEStringParserRuleCall_3_3_1_0_1() { return cIncomingsSequenceFlowEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//('outgoings' '(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'outgoings'
		public Keyword getOutgoingsKeyword_4_0() { return cOutgoingsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_4_2() { return cOutgoingsAssignment_4_2; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_4_2_0() { return cOutgoingsSequenceFlowCrossReference_4_2_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_4_2_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_4_2_0_1; }
		
		//("," outgoings+=[SequenceFlow|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//outgoings+=[SequenceFlow|EString]
		public Assignment getOutgoingsAssignment_4_3_1() { return cOutgoingsAssignment_4_3_1; }
		
		//[SequenceFlow|EString]
		public CrossReference getOutgoingsSequenceFlowCrossReference_4_3_1_0() { return cOutgoingsSequenceFlowCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getOutgoingsSequenceFlowEStringParserRuleCall_4_3_1_0_1() { return cOutgoingsSequenceFlowEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'sender'
		public Keyword getSenderKeyword_5() { return cSenderKeyword_5; }
		
		//sender=[servicesmetamodel::Role|EString]
		public Assignment getSenderAssignment_6() { return cSenderAssignment_6; }
		
		//[servicesmetamodel::Role|EString]
		public CrossReference getSenderRoleCrossReference_6_0() { return cSenderRoleCrossReference_6_0; }
		
		//EString
		public RuleCall getSenderRoleEStringParserRuleCall_6_0_1() { return cSenderRoleEStringParserRuleCall_6_0_1; }
		
		//'receiver'
		public Keyword getReceiverKeyword_7() { return cReceiverKeyword_7; }
		
		//receiver=[servicesmetamodel::Role|EString]
		public Assignment getReceiverAssignment_8() { return cReceiverAssignment_8; }
		
		//[servicesmetamodel::Role|EString]
		public CrossReference getReceiverRoleCrossReference_8_0() { return cReceiverRoleCrossReference_8_0; }
		
		//EString
		public RuleCall getReceiverRoleEStringParserRuleCall_8_0_1() { return cReceiverRoleEStringParserRuleCall_8_0_1; }
		
		//('targetOperation' targetOperation=[servicesmetamodel::Operation|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'targetOperation'
		public Keyword getTargetOperationKeyword_9_0() { return cTargetOperationKeyword_9_0; }
		
		//targetOperation=[servicesmetamodel::Operation|EString]
		public Assignment getTargetOperationAssignment_9_1() { return cTargetOperationAssignment_9_1; }
		
		//[servicesmetamodel::Operation|EString]
		public CrossReference getTargetOperationOperationCrossReference_9_1_0() { return cTargetOperationOperationCrossReference_9_1_0; }
		
		//EString
		public RuleCall getTargetOperationOperationEStringParserRuleCall_9_1_0_1() { return cTargetOperationOperationEStringParserRuleCall_9_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cImplementationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cImplementationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cImplementationActorCrossReference_4_1_0 = (CrossReference)cImplementationAssignment_4_1.eContents().get(0);
		private final RuleCall cImplementationActorEStringParserRuleCall_4_1_0_1 = (RuleCall)cImplementationActorCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Role servicesmetamodel::Role:
		//	{servicesmetamodel::Role}
		//	'Role'
		//	name=EString
		//	'{' ('implementation' implementation=[servicesmetamodel::Actor|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{servicesmetamodel::Role} 'Role' name=EString '{' ('implementation' implementation=[servicesmetamodel::Actor|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{servicesmetamodel::Role}
		public Action getRoleAction_0() { return cRoleAction_0; }
		
		//'Role'
		public Keyword getRoleKeyword_1() { return cRoleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('implementation' implementation=[servicesmetamodel::Actor|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'implementation'
		public Keyword getImplementationKeyword_4_0() { return cImplementationKeyword_4_0; }
		
		//implementation=[servicesmetamodel::Actor|EString]
		public Assignment getImplementationAssignment_4_1() { return cImplementationAssignment_4_1; }
		
		//[servicesmetamodel::Actor|EString]
		public CrossReference getImplementationActorCrossReference_4_1_0() { return cImplementationActorCrossReference_4_1_0; }
		
		//EString
		public RuleCall getImplementationActorEStringParserRuleCall_4_1_0_1() { return cImplementationActorEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Service");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperationsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOperationsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_4_2_0 = (RuleCall)cOperationsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOperationsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_4_3_1_0 = (RuleCall)cOperationsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Service servicesmetamodel::Service:
		//	{servicesmetamodel::Service}
		//	'Service'
		//	name=EString
		//	'{' ('operations' '{' operations+=Operation ("," operations+=Operation)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{servicesmetamodel::Service} 'Service' name=EString '{' ('operations' '{' operations+=Operation (","
		//operations+=Operation)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{servicesmetamodel::Service}
		public Action getServiceAction_0() { return cServiceAction_0; }
		
		//'Service'
		public Keyword getServiceKeyword_1() { return cServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('operations' '{' operations+=Operation ("," operations+=Operation)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'operations'
		public Keyword getOperationsKeyword_4_0() { return cOperationsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_4_2() { return cOperationsAssignment_4_2; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_4_2_0() { return cOperationsOperationParserRuleCall_4_2_0; }
		
		//("," operations+=Operation)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_4_3_1() { return cOperationsAssignment_4_3_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_4_3_1_0() { return cOperationsOperationParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUserAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUserKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//User servicesmetamodel::User:
		//	{servicesmetamodel::User}
		//	'User'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{servicesmetamodel::User} 'User' name=EString
		public Group getGroup() { return cGroup; }
		
		//{servicesmetamodel::User}
		public Action getUserAction_0() { return cUserAction_0; }
		
		//'User'
		public Keyword getUserKeyword_1() { return cUserKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cArgsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cArgsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cArgsEJavaObjectParserRuleCall_3_1_0 = (RuleCall)cArgsAssignment_3_1.eContents().get(0);
		private final Keyword cSideEffectKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSideEffectAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSideEffectEBooleanParserRuleCall_5_0 = (RuleCall)cSideEffectAssignment_5.eContents().get(0);
		private final Keyword cInvokingMsgKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInvokingMsgAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cInvokingMsgMessageCrossReference_7_0 = (CrossReference)cInvokingMsgAssignment_7.eContents().get(0);
		private final RuleCall cInvokingMsgMessageEStringParserRuleCall_7_0_1 = (RuleCall)cInvokingMsgMessageCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAnsweringMsgKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAnsweringMsgAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cAnsweringMsgMessageCrossReference_8_1_0 = (CrossReference)cAnsweringMsgAssignment_8_1.eContents().get(0);
		private final RuleCall cAnsweringMsgMessageEStringParserRuleCall_8_1_0_1 = (RuleCall)cAnsweringMsgMessageCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Operation servicesmetamodel::Operation:
		//	'Operation'
		//	name=EString
		//	'{' ('args' args=EJavaObject)?
		//	'sideEffect' sideEffect=EBoolean
		//	'invokingMsg' invokingMsg=[servicesmetamodel::Message|EString] ('answeringMsg'
		//	answeringMsg=[servicesmetamodel::Message|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Operation' name=EString '{' ('args' args=EJavaObject)? 'sideEffect' sideEffect=EBoolean 'invokingMsg'
		//invokingMsg=[servicesmetamodel::Message|EString] ('answeringMsg' answeringMsg=[servicesmetamodel::Message|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Operation'
		public Keyword getOperationKeyword_0() { return cOperationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('args' args=EJavaObject)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'args'
		public Keyword getArgsKeyword_3_0() { return cArgsKeyword_3_0; }
		
		//args=EJavaObject
		public Assignment getArgsAssignment_3_1() { return cArgsAssignment_3_1; }
		
		//EJavaObject
		public RuleCall getArgsEJavaObjectParserRuleCall_3_1_0() { return cArgsEJavaObjectParserRuleCall_3_1_0; }
		
		//'sideEffect'
		public Keyword getSideEffectKeyword_4() { return cSideEffectKeyword_4; }
		
		//sideEffect=EBoolean
		public Assignment getSideEffectAssignment_5() { return cSideEffectAssignment_5; }
		
		//EBoolean
		public RuleCall getSideEffectEBooleanParserRuleCall_5_0() { return cSideEffectEBooleanParserRuleCall_5_0; }
		
		//'invokingMsg'
		public Keyword getInvokingMsgKeyword_6() { return cInvokingMsgKeyword_6; }
		
		//invokingMsg=[servicesmetamodel::Message|EString]
		public Assignment getInvokingMsgAssignment_7() { return cInvokingMsgAssignment_7; }
		
		//[servicesmetamodel::Message|EString]
		public CrossReference getInvokingMsgMessageCrossReference_7_0() { return cInvokingMsgMessageCrossReference_7_0; }
		
		//EString
		public RuleCall getInvokingMsgMessageEStringParserRuleCall_7_0_1() { return cInvokingMsgMessageEStringParserRuleCall_7_0_1; }
		
		//('answeringMsg' answeringMsg=[servicesmetamodel::Message|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'answeringMsg'
		public Keyword getAnsweringMsgKeyword_8_0() { return cAnsweringMsgKeyword_8_0; }
		
		//answeringMsg=[servicesmetamodel::Message|EString]
		public Assignment getAnsweringMsgAssignment_8_1() { return cAnsweringMsgAssignment_8_1; }
		
		//[servicesmetamodel::Message|EString]
		public CrossReference getAnsweringMsgMessageCrossReference_8_1_0() { return cAnsweringMsgMessageCrossReference_8_1_0; }
		
		//EString
		public RuleCall getAnsweringMsgMessageEStringParserRuleCall_8_1_0_1() { return cAnsweringMsgMessageEStringParserRuleCall_8_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EJavaObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.EJavaObject");
		private final Keyword cEJavaObjectKeyword = (Keyword)rule.eContents().get(1);
		
		//EJavaObject ecore::EJavaObject:
		//	'EJavaObject' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EJavaObject'
		public Keyword getEJavaObjectKeyword() { return cEJavaObjectKeyword; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.chor4integration.textdsl.Chor4IntTxtDsl.Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMessageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMessageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cContentKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cContentAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cContentEJavaObjectParserRuleCall_3_1_0 = (RuleCall)cContentAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Message servicesmetamodel::Message:
		//	{servicesmetamodel::Message}
		//	'Message'
		//	'{' ('content' content=EJavaObject)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{servicesmetamodel::Message} 'Message' '{' ('content' content=EJavaObject)? '}'
		public Group getGroup() { return cGroup; }
		
		//{servicesmetamodel::Message}
		public Action getMessageAction_0() { return cMessageAction_0; }
		
		//'Message'
		public Keyword getMessageKeyword_1() { return cMessageKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('content' content=EJavaObject)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'content'
		public Keyword getContentKeyword_3_0() { return cContentKeyword_3_0; }
		
		//content=EJavaObject
		public Assignment getContentAssignment_3_1() { return cContentAssignment_3_1; }
		
		//EJavaObject
		public RuleCall getContentEJavaObjectParserRuleCall_3_1_0() { return cContentEJavaObjectParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private final ChoreographyElements pChoreography;
	private final FlowElementElements pFlowElement;
	private final FlowNodeElements pFlowNode;
	private final ActorElements pActor;
	private final EStringElements pEString;
	private final SequenceFlowElements pSequenceFlow;
	private final ExclusiveGatewayElements pExclusiveGateway;
	private final ParallelGatewayElements pParallelGateway;
	private final StartEventElements pStartEvent;
	private final EndEventElements pEndEvent;
	private final AtomicInteractionElements pAtomicInteraction;
	private final RoleElements pRole;
	private final ServiceElements pService;
	private final UserElements pUser;
	private final OperationElements pOperation;
	private final EJavaObjectElements pEJavaObject;
	private final EBooleanElements pEBoolean;
	private final MessageElements pMessage;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public Chor4IntTxtDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pChoreography = new ChoreographyElements();
		this.pFlowElement = new FlowElementElements();
		this.pFlowNode = new FlowNodeElements();
		this.pActor = new ActorElements();
		this.pEString = new EStringElements();
		this.pSequenceFlow = new SequenceFlowElements();
		this.pExclusiveGateway = new ExclusiveGatewayElements();
		this.pParallelGateway = new ParallelGatewayElements();
		this.pStartEvent = new StartEventElements();
		this.pEndEvent = new EndEventElements();
		this.pAtomicInteraction = new AtomicInteractionElements();
		this.pRole = new RoleElements();
		this.pService = new ServiceElements();
		this.pUser = new UserElements();
		this.pOperation = new OperationElements();
		this.pEJavaObject = new EJavaObjectElements();
		this.pEBoolean = new EBooleanElements();
		this.pMessage = new MessageElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.chor4integration.textdsl.Chor4IntTxtDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Choreography:
	//	{Choreography}
	//	'Choreography'
	//	'{' ('flowElements' '{' flowElements+=FlowElement ("," flowElements+=FlowElement)* '}')?
	//	'}';
	public ChoreographyElements getChoreographyAccess() {
		return pChoreography;
	}
	
	public ParserRule getChoreographyRule() {
		return getChoreographyAccess().getRule();
	}
	
	//FlowElement:
	//	SequenceFlow | ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction;
	public FlowElementElements getFlowElementAccess() {
		return pFlowElement;
	}
	
	public ParserRule getFlowElementRule() {
		return getFlowElementAccess().getRule();
	}
	
	//FlowNode:
	//	ExclusiveGateway | ParallelGateway | StartEvent | EndEvent | AtomicInteraction;
	public FlowNodeElements getFlowNodeAccess() {
		return pFlowNode;
	}
	
	public ParserRule getFlowNodeRule() {
		return getFlowNodeAccess().getRule();
	}
	
	//Actor servicesmetamodel::Actor:
	//	Service | User;
	public ActorElements getActorAccess() {
		return pActor;
	}
	
	public ParserRule getActorRule() {
		return getActorAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//SequenceFlow:
	//	'SequenceFlow'
	//	name=EString
	//	'{'
	//	'target' target=[FlowNode|EString]
	//	'source' source=[FlowNode|EString]
	//	'}';
	public SequenceFlowElements getSequenceFlowAccess() {
		return pSequenceFlow;
	}
	
	public ParserRule getSequenceFlowRule() {
		return getSequenceFlowAccess().getRule();
	}
	
	//ExclusiveGateway:
	//	{ExclusiveGateway}
	//	'ExclusiveGateway'
	//	name=EString
	//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
	//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
	//	'}';
	public ExclusiveGatewayElements getExclusiveGatewayAccess() {
		return pExclusiveGateway;
	}
	
	public ParserRule getExclusiveGatewayRule() {
		return getExclusiveGatewayAccess().getRule();
	}
	
	//ParallelGateway:
	//	{ParallelGateway}
	//	'ParallelGateway'
	//	name=EString
	//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
	//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
	//	'}';
	public ParallelGatewayElements getParallelGatewayAccess() {
		return pParallelGateway;
	}
	
	public ParserRule getParallelGatewayRule() {
		return getParallelGatewayAccess().getRule();
	}
	
	//StartEvent:
	//	{StartEvent}
	//	'StartEvent'
	//	name=EString
	//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
	//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
	//	'}';
	public StartEventElements getStartEventAccess() {
		return pStartEvent;
	}
	
	public ParserRule getStartEventRule() {
		return getStartEventAccess().getRule();
	}
	
	//EndEvent:
	//	{EndEvent}
	//	'EndEvent'
	//	name=EString
	//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
	//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
	//	'}';
	public EndEventElements getEndEventAccess() {
		return pEndEvent;
	}
	
	public ParserRule getEndEventRule() {
		return getEndEventAccess().getRule();
	}
	
	//AtomicInteraction:
	//	'AtomicInteraction'
	//	name=EString
	//	'{' ('incomings' '(' incomings+=[SequenceFlow|EString] ("," incomings+=[SequenceFlow|EString])* ')')? ('outgoings'
	//	'(' outgoings+=[SequenceFlow|EString] ("," outgoings+=[SequenceFlow|EString])* ')')?
	//	'sender' sender=[servicesmetamodel::Role|EString]
	//	'receiver' receiver=[servicesmetamodel::Role|EString] ('targetOperation'
	//	targetOperation=[servicesmetamodel::Operation|EString])?
	//	'}';
	public AtomicInteractionElements getAtomicInteractionAccess() {
		return pAtomicInteraction;
	}
	
	public ParserRule getAtomicInteractionRule() {
		return getAtomicInteractionAccess().getRule();
	}
	
	//Role servicesmetamodel::Role:
	//	{servicesmetamodel::Role}
	//	'Role'
	//	name=EString
	//	'{' ('implementation' implementation=[servicesmetamodel::Actor|EString])?
	//	'}';
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//Service servicesmetamodel::Service:
	//	{servicesmetamodel::Service}
	//	'Service'
	//	name=EString
	//	'{' ('operations' '{' operations+=Operation ("," operations+=Operation)* '}')?
	//	'}';
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//User servicesmetamodel::User:
	//	{servicesmetamodel::User}
	//	'User'
	//	name=EString;
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//Operation servicesmetamodel::Operation:
	//	'Operation'
	//	name=EString
	//	'{' ('args' args=EJavaObject)?
	//	'sideEffect' sideEffect=EBoolean
	//	'invokingMsg' invokingMsg=[servicesmetamodel::Message|EString] ('answeringMsg'
	//	answeringMsg=[servicesmetamodel::Message|EString])?
	//	'}';
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//EJavaObject ecore::EJavaObject:
	//	'EJavaObject' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EJavaObjectElements getEJavaObjectAccess() {
		return pEJavaObject;
	}
	
	public ParserRule getEJavaObjectRule() {
		return getEJavaObjectAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Message servicesmetamodel::Message:
	//	{servicesmetamodel::Message}
	//	'Message'
	//	'{' ('content' content=EJavaObject)?
	//	'}';
	public MessageElements getMessageAccess() {
		return pMessage;
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
