/**
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class Chor4IntTxtDslQuickfixProvider extends DefaultQuickfixProvider {
}
