/*
 * generated by Xtext 2.12.0
 */
package com.chor4integration.textdsl.ide.contentassist.antlr;

import com.chor4integration.textdsl.ide.contentassist.antlr.internal.InternalChor4IntTxtDslParser;
import com.chor4integration.textdsl.services.Chor4IntTxtDslGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class Chor4IntTxtDslParser extends AbstractContentAssistParser {

	@Inject
	private Chor4IntTxtDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalChor4IntTxtDslParser createParser() {
		InternalChor4IntTxtDslParser result = new InternalChor4IntTxtDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFlowElementAccess().getAlternatives(), "rule__FlowElement__Alternatives");
					put(grammarAccess.getActorAccess().getAlternatives(), "rule__Actor__Alternatives");
					put(grammarAccess.getFlowNodeAccess().getAlternatives(), "rule__FlowNode__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getChoreographyAccess().getGroup(), "rule__Choreography__Group__0");
					put(grammarAccess.getChoreographyAccess().getGroup_3(), "rule__Choreography__Group_3__0");
					put(grammarAccess.getChoreographyAccess().getGroup_3_3(), "rule__Choreography__Group_3_3__0");
					put(grammarAccess.getChoreographyAccess().getGroup_4(), "rule__Choreography__Group_4__0");
					put(grammarAccess.getChoreographyAccess().getGroup_4_3(), "rule__Choreography__Group_4_3__0");
					put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
					put(grammarAccess.getRoleAccess().getGroup_4(), "rule__Role__Group_4__0");
					put(grammarAccess.getSequenceFlowAccess().getGroup(), "rule__SequenceFlow__Group__0");
					put(grammarAccess.getExclusiveGatewayAccess().getGroup(), "rule__ExclusiveGateway__Group__0");
					put(grammarAccess.getExclusiveGatewayAccess().getGroup_4(), "rule__ExclusiveGateway__Group_4__0");
					put(grammarAccess.getExclusiveGatewayAccess().getGroup_4_3(), "rule__ExclusiveGateway__Group_4_3__0");
					put(grammarAccess.getExclusiveGatewayAccess().getGroup_5(), "rule__ExclusiveGateway__Group_5__0");
					put(grammarAccess.getExclusiveGatewayAccess().getGroup_5_3(), "rule__ExclusiveGateway__Group_5_3__0");
					put(grammarAccess.getParallelGatewayAccess().getGroup(), "rule__ParallelGateway__Group__0");
					put(grammarAccess.getParallelGatewayAccess().getGroup_4(), "rule__ParallelGateway__Group_4__0");
					put(grammarAccess.getParallelGatewayAccess().getGroup_4_3(), "rule__ParallelGateway__Group_4_3__0");
					put(grammarAccess.getParallelGatewayAccess().getGroup_5(), "rule__ParallelGateway__Group_5__0");
					put(grammarAccess.getParallelGatewayAccess().getGroup_5_3(), "rule__ParallelGateway__Group_5_3__0");
					put(grammarAccess.getStartEventAccess().getGroup(), "rule__StartEvent__Group__0");
					put(grammarAccess.getStartEventAccess().getGroup_4(), "rule__StartEvent__Group_4__0");
					put(grammarAccess.getStartEventAccess().getGroup_4_3(), "rule__StartEvent__Group_4_3__0");
					put(grammarAccess.getStartEventAccess().getGroup_5(), "rule__StartEvent__Group_5__0");
					put(grammarAccess.getStartEventAccess().getGroup_5_3(), "rule__StartEvent__Group_5_3__0");
					put(grammarAccess.getEndEventAccess().getGroup(), "rule__EndEvent__Group__0");
					put(grammarAccess.getEndEventAccess().getGroup_4(), "rule__EndEvent__Group_4__0");
					put(grammarAccess.getEndEventAccess().getGroup_4_3(), "rule__EndEvent__Group_4_3__0");
					put(grammarAccess.getEndEventAccess().getGroup_5(), "rule__EndEvent__Group_5__0");
					put(grammarAccess.getEndEventAccess().getGroup_5_3(), "rule__EndEvent__Group_5_3__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup(), "rule__AtomicInteraction__Group__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup_3(), "rule__AtomicInteraction__Group_3__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup_3_3(), "rule__AtomicInteraction__Group_3_3__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup_4(), "rule__AtomicInteraction__Group_4__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup_4_3(), "rule__AtomicInteraction__Group_4_3__0");
					put(grammarAccess.getAtomicInteractionAccess().getGroup_9(), "rule__AtomicInteraction__Group_9__0");
					put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
					put(grammarAccess.getOperationAccess().getGroup_7(), "rule__Operation__Group_7__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageAccess().getGroup_3(), "rule__Message__Group_3__0");
					put(grammarAccess.getMessageAccess().getGroup_3_3(), "rule__Message__Group_3_3__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_3(), "rule__Parameter__Group_3__0");
					put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
					put(grammarAccess.getServiceAccess().getGroup_4(), "rule__Service__Group_4__0");
					put(grammarAccess.getServiceAccess().getGroup_4_3(), "rule__Service__Group_4_3__0");
					put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
					put(grammarAccess.getChoreographyAccess().getFlowElementsAssignment_3_2(), "rule__Choreography__FlowElementsAssignment_3_2");
					put(grammarAccess.getChoreographyAccess().getFlowElementsAssignment_3_3_1(), "rule__Choreography__FlowElementsAssignment_3_3_1");
					put(grammarAccess.getChoreographyAccess().getRolesAssignment_4_2(), "rule__Choreography__RolesAssignment_4_2");
					put(grammarAccess.getChoreographyAccess().getRolesAssignment_4_3_1(), "rule__Choreography__RolesAssignment_4_3_1");
					put(grammarAccess.getRoleAccess().getNameAssignment_2(), "rule__Role__NameAssignment_2");
					put(grammarAccess.getRoleAccess().getActorAssignment_4_1(), "rule__Role__ActorAssignment_4_1");
					put(grammarAccess.getSequenceFlowAccess().getNameAssignment_1(), "rule__SequenceFlow__NameAssignment_1");
					put(grammarAccess.getSequenceFlowAccess().getTargetAssignment_4(), "rule__SequenceFlow__TargetAssignment_4");
					put(grammarAccess.getSequenceFlowAccess().getSourceAssignment_6(), "rule__SequenceFlow__SourceAssignment_6");
					put(grammarAccess.getExclusiveGatewayAccess().getNameAssignment_2(), "rule__ExclusiveGateway__NameAssignment_2");
					put(grammarAccess.getExclusiveGatewayAccess().getIncomingsAssignment_4_2(), "rule__ExclusiveGateway__IncomingsAssignment_4_2");
					put(grammarAccess.getExclusiveGatewayAccess().getIncomingsAssignment_4_3_1(), "rule__ExclusiveGateway__IncomingsAssignment_4_3_1");
					put(grammarAccess.getExclusiveGatewayAccess().getOutgoingsAssignment_5_2(), "rule__ExclusiveGateway__OutgoingsAssignment_5_2");
					put(grammarAccess.getExclusiveGatewayAccess().getOutgoingsAssignment_5_3_1(), "rule__ExclusiveGateway__OutgoingsAssignment_5_3_1");
					put(grammarAccess.getParallelGatewayAccess().getNameAssignment_2(), "rule__ParallelGateway__NameAssignment_2");
					put(grammarAccess.getParallelGatewayAccess().getIncomingsAssignment_4_2(), "rule__ParallelGateway__IncomingsAssignment_4_2");
					put(grammarAccess.getParallelGatewayAccess().getIncomingsAssignment_4_3_1(), "rule__ParallelGateway__IncomingsAssignment_4_3_1");
					put(grammarAccess.getParallelGatewayAccess().getOutgoingsAssignment_5_2(), "rule__ParallelGateway__OutgoingsAssignment_5_2");
					put(grammarAccess.getParallelGatewayAccess().getOutgoingsAssignment_5_3_1(), "rule__ParallelGateway__OutgoingsAssignment_5_3_1");
					put(grammarAccess.getStartEventAccess().getNameAssignment_2(), "rule__StartEvent__NameAssignment_2");
					put(grammarAccess.getStartEventAccess().getIncomingsAssignment_4_2(), "rule__StartEvent__IncomingsAssignment_4_2");
					put(grammarAccess.getStartEventAccess().getIncomingsAssignment_4_3_1(), "rule__StartEvent__IncomingsAssignment_4_3_1");
					put(grammarAccess.getStartEventAccess().getOutgoingsAssignment_5_2(), "rule__StartEvent__OutgoingsAssignment_5_2");
					put(grammarAccess.getStartEventAccess().getOutgoingsAssignment_5_3_1(), "rule__StartEvent__OutgoingsAssignment_5_3_1");
					put(grammarAccess.getEndEventAccess().getNameAssignment_2(), "rule__EndEvent__NameAssignment_2");
					put(grammarAccess.getEndEventAccess().getIncomingsAssignment_4_2(), "rule__EndEvent__IncomingsAssignment_4_2");
					put(grammarAccess.getEndEventAccess().getIncomingsAssignment_4_3_1(), "rule__EndEvent__IncomingsAssignment_4_3_1");
					put(grammarAccess.getEndEventAccess().getOutgoingsAssignment_5_2(), "rule__EndEvent__OutgoingsAssignment_5_2");
					put(grammarAccess.getEndEventAccess().getOutgoingsAssignment_5_3_1(), "rule__EndEvent__OutgoingsAssignment_5_3_1");
					put(grammarAccess.getAtomicInteractionAccess().getNameAssignment_1(), "rule__AtomicInteraction__NameAssignment_1");
					put(grammarAccess.getAtomicInteractionAccess().getIncomingsAssignment_3_2(), "rule__AtomicInteraction__IncomingsAssignment_3_2");
					put(grammarAccess.getAtomicInteractionAccess().getIncomingsAssignment_3_3_1(), "rule__AtomicInteraction__IncomingsAssignment_3_3_1");
					put(grammarAccess.getAtomicInteractionAccess().getOutgoingsAssignment_4_2(), "rule__AtomicInteraction__OutgoingsAssignment_4_2");
					put(grammarAccess.getAtomicInteractionAccess().getOutgoingsAssignment_4_3_1(), "rule__AtomicInteraction__OutgoingsAssignment_4_3_1");
					put(grammarAccess.getAtomicInteractionAccess().getSenderAssignment_6(), "rule__AtomicInteraction__SenderAssignment_6");
					put(grammarAccess.getAtomicInteractionAccess().getReceiverAssignment_8(), "rule__AtomicInteraction__ReceiverAssignment_8");
					put(grammarAccess.getAtomicInteractionAccess().getTargetOperationAssignment_9_1(), "rule__AtomicInteraction__TargetOperationAssignment_9_1");
					put(grammarAccess.getOperationAccess().getNameAssignment_1(), "rule__Operation__NameAssignment_1");
					put(grammarAccess.getOperationAccess().getSideEffectAssignment_4(), "rule__Operation__SideEffectAssignment_4");
					put(grammarAccess.getOperationAccess().getInvokingMsgAssignment_6(), "rule__Operation__InvokingMsgAssignment_6");
					put(grammarAccess.getOperationAccess().getAnsweringMsgAssignment_7_1(), "rule__Operation__AnsweringMsgAssignment_7_1");
					put(grammarAccess.getMessageAccess().getParameterAssignment_3_2(), "rule__Message__ParameterAssignment_3_2");
					put(grammarAccess.getMessageAccess().getParameterAssignment_3_3_1(), "rule__Message__ParameterAssignment_3_3_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_3_1(), "rule__Parameter__TypeAssignment_3_1");
					put(grammarAccess.getServiceAccess().getNameAssignment_2(), "rule__Service__NameAssignment_2");
					put(grammarAccess.getServiceAccess().getOperationsAssignment_4_2(), "rule__Service__OperationsAssignment_4_2");
					put(grammarAccess.getServiceAccess().getOperationsAssignment_4_3_1(), "rule__Service__OperationsAssignment_4_3_1");
					put(grammarAccess.getUserAccess().getNameAssignment_2(), "rule__User__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Chor4IntTxtDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Chor4IntTxtDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
